config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :articles do
    collection do
      get :bbs
    end
  end
  redirect_to_bbs_article = redirect {|path_params, req| "/articles/bbs?#{req.env['QUERY_STRING']}" }
  get '/bbs_article_body.php', to: redirect_to_bbs_article
  get '/bbs_article_index.php', to: redirect_to_bbs_article
  get '/bbs_article.php', to: redirect_to_bbs_article
  get '/bbs.php', to: redirect('/articles')
  get '/log.php', to: redirect('/')
  resources :topics
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  acts_as_nested_set counter_cache: :children_count

  validates :remote_addr, presence: true
  validates :name, :subject, :body, presence: true
  validates :name, length: { maximum: 30 }
  validates :subject, length: { maximum: 50 }
  validates :body, length: { maximum: 2000 }
  validates :mail_addr, length: { maximum: 100 }
  validates :url, length: { maximum: 100 }

  validates :article_id, :pthread_id, presence: true

  NEW_ARTICLE_TIME = 24
  ARTICLE_MAX = 100

  def commentable?
    root.self_and_descendants.count < ARTICLE_MAX
  end

  def set_ids
    parent = self.parent
    if parent
      if !parent.commentable?
        return false
      end
      self.pthread_id = parent.pthread_id
      self.article_id = parent.self_and_descendants.count + 1
    else
      self.pthread_id = Article.roots.count + 1
      self.article_id = 1
    end
    true
  end

  after_save :touch_root
  def touch_root
    root.touch if parent_id
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :body, presence: true

  def self.most_recent
    where(delete_flg: false).order(:updated_at).last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
# coding: utf-8
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.where(parent_id: nil, delete_flg: false)
    @q = @articles.ransack(params[:q])
    @q.sorts = 'updated_at desc' if @q.sorts.empty?
    @articles = @q.result(distinct: true)
    @articles = @articles.page(params[:page]).per(50)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    unless @article.root?
      redirect_to "#{url_for(@article.root)}#id#{@article.id}"
    end
  end

  # GET /articles/new
  def new
    @article = Article.new
    parent_id = params[:parent_id]
    if parent_id
      parent = Article.find(parent_id)
      @article.parent = parent
      unless parent.commentable?
        redirect_to parent, notice: "コメント数が#{Article::ARTICLE_MAX}を超えています。これ以上は投稿できません。"
        return
      end
      if parent.article_id != 1
        @article.subject = 'Re: ' + parent.subject.sub(/\ARe: /, '')
      end
    end
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.remote_addr = request.remote_ip
    if !@article.set_ids
      redirect_to @article.parent, notice: "コメント数が#{Article::ARTICLE_MAX}を超えています。これ以上は投稿できません。"
      return
    end
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def bbs
    h = {}
    h[:pthread_id] = params[:pthread_id].to_i
    article_id = params[:article_id]
    if article_id
      h[:article_id] = article_id.to_i
    end
    redirect_to Article.where(h).first
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:parent_id, :name, :subject, :body, :mail_addr, :url)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:body, :delete_flg)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = I18n.t(:'nav.site_name')
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  def nav_link_to(name, path)
    active = request.path == path
    nav_item_html_class = active ? 'nav-item active' : 'nav-item'
    content_tag(:li, class: nav_item_html_class) do
      link_to path, class: 'nav-link' do
        if active
          h(name) + content_tag(:span, '(current)', class: 'sr-only')
        else
          name
        end
      end
    end
  end
end

app/views/articles/_article.html.slim
.card.mb-3 id="id#{article.id}"
  .card-header
    = "#{article.article_id}. #{article.subject}"
  .card-body
    h5.card-title
      = '投稿者: '
      - if article.mail_addr?
        = link_to article.name, "mailto:#{article.mail_addr}"
      - else
        = article.name
      - if article.url?
        '
        = link_to '<HOME>', article.url, class: 'card-link', rel: 'nofollow'
    h6.card-subtitle.mb-2.text-muted
      = '投稿日時: '
      = l article.created_at
    p.card-text
      = article.body
  - if commentable
    .card-footer.text-right
      = link_to new_article_path(parent_id: article.id), class: 'card-link btn btn-outline-secondary', rel: 'nofollow' do
        small このコメントに返信

app/views/articles/_form.html.slim
= simple_form_for(@article, wrapper: 'horizontal_form') do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.hidden_field :parent_id
    /= f.input :delete_flg
    /= f.input :password
    = f.input :name
    = f.input :mail_addr
    = f.input :subject
    = f.input :body, input_html: { rows: 15 }
    = f.input :url

  .form-actions
    = f.button :submit, class: 'btn btn-primary'

.text-secondary.text-right style="font-size:small"
  p ※ 名前、タイトル、内容は必ず記入してください。
  p ※ 宣伝、広告を目的とした書き込みには費用を請求することがあります。

app/views/articles/edit.html.slim
h1 Editing article

== render 'form'

=> link_to 'Show', @article
'|
=< link_to 'Back', articles_path

app/views/articles/index.html.slim
h2 ☆掲示板

p
  = link_to 'Sylpheed', 'https://sylpheed.sraoss.jp/'
  | に関するご質問、ご要望、ご指摘等に関する掲示板です。
p
  | 本サイトにある
  = link_to 'マニュアル類', '/doc.php'
  | に関するご質問、ご要望、ご指摘等もこちらで受け付けております。
p
  = link_to 'Sylpheed', 'https://sylpheed.sraoss.jp/'
  | に関するお問い合わせは
  = link_to 'メーリングリスト', 'https://sylpheed.sraoss.jp/ja/ml.html'
  | からも行えます。

= page_entries_info @articles
= paginate @articles

table.table
  thead
    tr
      th = sort_link @q, :pthread_id
      th 作成者
      th = sort_link @q, :updated_at
      th 記事数

  tbody
    - threshold = Time.current - Article::NEW_ARTICLE_TIME.hours
    - @articles.each do |article|
      tr
        td = link_to article do
          = "#{article.pthread_id}. #{article.subject}"
          - if threshold < article.updated_at
            span.text-danger  ★
        td = article.name
        td = l article.updated_at
        td.text-right = article.self_and_descendants.count

p.p-3.mb-2.bg-light.text-dark
  span.text-danger ★
  | は#{Article::NEW_ARTICLE_TIME}時間以内に投稿のあったスレッドです。

= link_to '新規スレッド作成', new_article_path, class: 'btn btn-outline-secondary'

app/views/articles/new.html.slim
- if @article.parent_id?
  h2 ☆コメント投稿
  == render partial: 'article', object: @article.parent, locals: { commentable: false }
- else
  h2 ☆スレッド作成

== render 'form'

app/views/articles/show.html.slim
.row
  .col-12.col-md-3.col-xl-2
    h4.small コメント一覧
    ul.list-unstyled style="overflow-x: scroll"
      - threshold = Time.current - Article::NEW_ARTICLE_TIME.hours
      - Article.each_with_level(@article.self_and_descendants) do |article, level|
        li.text-nowrap
          - if level > 0
            - if threshold < article.updated_at
              span.text-danger ★
            - else
              = '　'
            = '　' * (level - 1) + '└ '
          = link_to "#{article.article_id}. #{article.subject}", "\#id#{article.id}"
          |  : #{article.name} (#{l article.created_at})
    =< link_to 'スレッド一覧へ戻る', articles_path

  .col-12.col-md-9.col-xl-8
    h4
      = "スレッドNo.#{@article.pthread_id}: #{@article.subject}"
    - commentable = @article.commentable?
    - if commentable
      .text-right.mb-3
        = link_to new_article_path(parent_id: @article.id), class: 'btn btn-outline-secondary' do
          small 新規コメント投稿
    - else
      .alert.alert-info role="alert" style="background-color:#cce7ff"
        | コメント数が#{Article::ARTICLE_MAX}を超えています。これ以上は投稿できません

    - @article.self_and_descendants.each do |child|
      == render partial: 'article', object: child, locals: { commentable: commentable && @article != child }
    =< link_to 'スレッド一覧へ戻る', articles_path

app/views/layouts/_flash.html.slim
- if flash[:alert]
  .alert.alert-danger role="alert"
    = flash[:alert]
- if flash[:notice]
  .alert.alert-warning role="alert"
    = flash[:notice]

app/views/layouts/_footer.html.slim
footer
  section.copyright
    = link_to about_path, class: 'text-muted' do
      | All content copyright #{t(:'nav.site_name')} &copy; 2018 &bull; All rights reserved.

app/views/layouts/_nav.html.slim
h1= t(:'nav.site_name')
nav.navbar.navbar-expand-md.navbar-light.mb-4 style="background-color:#ddeeff"
  button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation"]
    span.navbar-toggler-icon
  #navbarCollapse.collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      = nav_link_to t(:'nav.home'), root_path
      = nav_link_to t(:'nav.bbs'), articles_path
      = nav_link_to t(:'nav.manual'), '#manual'
      = nav_link_to t(:'nav.faq'), '#faq'
      = nav_link_to t(:'nav.sylpheed'), 'https://sylpheed.sraoss.jp/'

app/views/layouts/application.html.slim
doctype html
html lang='ja'
  head
    meta charset='utf-8'
    title
      = full_title(yield(:title))
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    == render partial: 'layouts/nav'
    == render partial: 'layouts/flash'
    main.container-fluid#main
      = yield
    == render partial: 'layouts/footer'

app/views/static_pages/_about.html.slim
h2 ☆本サイトについて
p
  | 本サイトは
  = link_to 'Sylpheed', 'http://sylpheed.good-day.net/'
  | (X Window System上で動作する電子メールクライアント&ニュースリーダ)のユーザのためのサポートサイトです。
p 本サイトには以下のコンテンツが含まれています。
.list-group
  = link_to '掲示板: Sylpheedに関する掲示板', articles_path, class: 'list-group-item list-group-item-action'
  = link_to 'マニュアル: Sylpheedに関するフリーのマニュアル類', '#doc', class: 'list-group-item list-group-item-action'
  = link_to 'FAQ: Sylpheedに関するよくある質問と回答', '#faq', class: 'list-group-item list-group-item-action'
p
  | 本サイトに関するご指摘、ご質問、ご要望に関しましては本サイトの
  = link_to '掲示板', articles_path
  | か、
  = link_to 'webmaster@good-day.net', 'mailto:webmaster@good-day.net'
  | までお問い合わせください。

app/views/static_pages/about.html.slim
- provide(:title, t(:'nav.about'))
== render partial: 'about'

app/views/static_pages/home.html.slim
== render partial: 'about'
h2 ☆Sylpheed NEWS
== Topic.most_recent&.body

app/views/topics/_form.html.slim
= simple_form_for(@topic) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :body
    = f.input :delete_flg

  .form-actions
    = f.button :submit

app/views/topics/edit.html.slim
h1 Editing topic

== render 'form'

=> link_to 'Show', @topic
'|
=< link_to 'Back', topics_path

app/views/topics/index.html.slim
h1 Listing topics

table
  thead
    tr
      th Body
      th Delete flg
      th
      th
      th

  tbody
    - @topics.each do |topic|
      tr
        td = topic.body
        td = topic.delete_flg
        td = link_to 'Show', topic
        td = link_to 'Edit', edit_topic_path(topic)
        td = link_to 'Destroy', topic, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Topic', new_topic_path

app/views/topics/new.html.slim
h1 New topic

== render 'form'

= link_to 'Back', topics_path

app/views/topics/show.html.slim
p#notice = notice

p
  strong Body:
  = @topic.body
p
  strong Delete flg:
  = @topic.delete_flg

=> link_to 'Edit', edit_topic_path(@topic)
'|
=< link_to 'Back', topics_path